rootfs_configs:
  buster:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - amd64
      - arm64
      - armel
      - armhf
      - i386
      - mips
      - mipsel
      - mips64el
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
      - klibc-utils
      - libext2fs2
      - libgnutls30
      - libklibc
      - libncursesw6
      - libp11-kit0
      - libunistring2
      - sensible-utils
    extra_files_remove:
      - '*networkd*'
      - '*resolved*'
      - tar
      - patch
      - dir
      - partx
      - find
    script: "scripts/install-bootrr.sh"

  buster-v4l2:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
    script: "scripts/buster-v4l2.sh"
    test_overlay: "overlays/v4l2"

  buster-igt:
    rootfs_type: debos
    debian_release: buster
    arch_list:
        - amd64
        - armhf
        - arm64
        - mips
    extra_packages:
        - libcairo2
        - libdw1
        - libglib2.0-0
        - libpciaccess0
        - libprocps7
        - libudev1
        - libunwind8
    extra_packages_remove:
        - bash
        - e2fslibs
        - e2fsprogs
        - fonts-dejavu-core
        - klibc-utils
        - libext2fs2
        - libgio3.0-cil
        - libgnutls30
        - libklibc
        - libncursesw6
        - libp11-kit0
        - libunistring2
        - libx11-data
        - sensible-utils
    extra_files_remove:
        - '*networkd*'
        - '*resolved*'
        - tar
        - patch
        - diff
        - dir
        - partx
        - find
    script: "scripts/buster-igt.sh"
    test_overlay: "overlays/igt"

  buster-cros-ec:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages:
      - python3-minimal
      - python3-unittest2
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
      - libext2fs2
    script: "scripts/buster-cros-ec-tests.sh"
    test_overlay: ""
