---
- name: Install ufw package
  apt:  pkg=ufw
        state=latest
        update_cache=yes
  tags:
    - firewall
    - deps

- name: Fix default config file
  lineinfile: dest=/etc/default/ufw
              backup=yes
              regexp=^IPT_SYSCTL=
              state=present
              line=IPT_SYSCTL=/etc/sysctl.conf
  tags:
    - firewall

- name: Enable logging
  ufw: logging=low
  tags:
    - firewall

- name: Allow dns traffic
  ufw:  rule=allow
        port=53
  tags:
    - firewall

- name: Allow ssh connections
  ufw:  rule=allow
        port=22
        proto=tcp
  tags:
    - firewall

- name: Rate limit ssh connections
  ufw:  rule=limit
        port=22
        proto=tcp
  tags:
    - firewall

- name: Accept web connections
  ufw:  rule=allow
        port=80
        proto=tcp
  tags:
    - firewall

- name: Accept web secure connections
  when: role == "production"
  ufw:  rule=allow
        port=443
        proto=tcp
  tags:
    - firewall

- name: Deny auth traffic and log it
  ufw:  rule=reject
        port=auth
        log=yes
  tags:
    - firewall

- name: Accept Zabbix traffic
  ufw:  rule=allow
        direction=in
        from={{ zabbix_ip }}
        port=10050
  when: role == "production"
  tags:
    - firewall

- name: Enable ufw
  ufw: state=enabled
  tags:
    - firewall
