trees:
  cip:
    url: "https://git.kernel.org/pub/scm/linux/kernel/git/cip/linux-cip.git"

  cip-gitlab:
    url: "https://gitlab.com/cip-project/cip-kernel/linux-cip.git"


# Build fewer kernel configs with cip branches
cip_variants: &cip_variants
  gcc-10: &cip_gcc_10
    build_environment: gcc-10
    fragments: [tinyconfig]
    architectures: &cip_architectures
      arc:
        base_defconfig: 'haps_hs_smp_defconfig'
        extra_configs: ['allnoconfig']
        filters:
          # remove any non-ARCv2 defconfigs since we only have ARCv2 toolchain
          - blocklist:
              defconfig:
                - 'axs101_defconfig'
                - 'nps_defconfig'
                - 'nsim_700_defconfig'
                - 'nsimosci_defconfig'
                - 'tb10x_defconfig'
      arm: &cip_variants_arch_arm
        base_defconfig: 'multi_v7_defconfig'
        extra_configs: ['allnoconfig']
      arm64:
        fragments: [arm64-chromebook]
        extra_configs: ['allnoconfig']
        filters:
          - blocklist:
              kernel: ['v4.4']
      i386:
        base_defconfig: 'i386_defconfig'
        extra_configs: ['allnoconfig']
      mips: &cip_variants_arch_mips
        base_defconfig: '32r2el_defconfig'
        extra_configs: ['allnoconfig']
        filters:
          - blocklist: {defconfig: ['generic_defconfig']}
      riscv:
        extra_configs: ['allnoconfig']
        filters:
          - blocklist:
              kernel: ['v3.', 'v4.4', 'v4.9', 'v4.14']
      x86_64:
        base_defconfig: 'x86_64_defconfig'
        fragments: [x86-chromebook]
        extra_configs: ['allnoconfig']


cip_variants_kselftest: &cip_variants_kselftest
  gcc-10:
    <<: *cip_gcc_10
    architectures:
      <<: *cip_architectures
      arm:
        base_defconfig: 'multi_v7_defconfig'
        fragments: [kselftest]
        extra_configs: ['allnoconfig']
      arm64:
        fragments: [kselftest, arm64-chromebook]
        extra_configs:
          - 'allnoconfig'
          - 'defconfig+arm64-chromebook+kselftest'
      x86_64:
        base_defconfig: 'x86_64_defconfig'
        fragments: [kselftest, x86-chromebook]
        extra_configs:
          - 'allnoconfig'
          - 'x86_64_defconfig+x86-chromebook+kselftest'


cip_variants_preempt_rt: &cip_variants_preempt_rt
  gcc-10:
    <<: *cip_gcc_10
    fragments: [preempt_rt]
    architectures: &cip_architectures_preempt_rt
      <<: *cip_architectures
      arm: &cip_variants_preempt_rt_arch_arm
        fragments: [preempt_rt]
        extra_configs:
          - 'multi_v7_defconfig+preempt_rt'
      arm64:
        fragments: [preempt_rt]
        extra_configs:
          - 'defconfig+preempt_rt'
      x86_64:
        fragments: [preempt_rt, x86-chromebook]
        extra_configs:
          - 'x86_64_defconfig+preempt_rt'
          - 'x86_64_defconfig+x86-chromebook+preempt_rt'

cip_variants_4_4: &cip_variants_4_4
  gcc-10: &cip_variants_4_4_gcc-10
    <<: *cip_gcc_10
    architectures:
      <<: *cip_architectures
      arm:
        <<: *cip_variants_arch_arm
        filters: &cip_4_4_arm_filters
          - blocklist:
              defconfig:
                - 'rpc_defconfig' # gcc-10 not supported
      mips:
        <<: *cip_variants_arch_mips
        filters: &cip_4_4_mips_filters
          - blocklist:
              defconfig:
                - 'generic_defconfig'
                - 'fuloong2e_defconfig' # gcc-10 not supported
                - 'ip27_defconfig' # unknown target uImage.gz
                - 'ip28_defconfig' # unknown target uImage.gz
                - 'lemote2f_defconfig' # gcc-10 not supported

cip_variants_4_4_preempt_rt: &cip_variants_4_4_preempt_rt
  <<: *cip_variants_preempt_rt
  gcc-10:
    <<: *cip_variants_4_4_gcc-10
    fragments: [preempt_rt]
    architectures:
      <<: *cip_architectures_preempt_rt
      arm:
        <<: *cip_variants_preempt_rt_arch_arm
        filters: *cip_4_4_arm_filters
      mips:
        <<: *cip_variants_arch_mips
        filters: *cip_4_4_mips_filters

build_configs:
  cip_4.4:
    tree: cip
    branch: 'linux-4.4.y-cip'
    variants: *cip_variants_4_4

  cip_4.4-rc:
    tree: cip-gitlab
    branch: 'ci/iwamatsu/linux-4.4.y-cip-rc'
    variants: *cip_variants_4_4

  cip_4.4-rt:
    tree: cip
    branch: 'linux-4.4.y-cip-rt'
    variants: *cip_variants_4_4_preempt_rt

  cip_4.19:
    tree: cip
    branch: 'linux-4.19.y-cip'
    variants:
      gcc-10:
        build_environment: gcc-10
        architectures:
          arm:
            base_defconfig: 'multi_v7_defconfig'
            extra_configs:
              - 'allnoconfig'
              - 'cip://4.19.y-cip/arm/qemu_arm_defconfig'
          arm64:
            fragments: [arm64-chromebook]
            extra_configs:
              - 'allnoconfig'
              - 'cip://4.19.y-cip/arm64/qemu_arm64_defconfig'
          x86_64:
            base_defconfig: 'x86_64_defconfig'
            fragments: [x86-chromebook]
            extra_configs:
              - 'allnoconfig'
              - 'cip://4.19.y-cip/x86/cip_qemu_defconfig'

  cip_4.19-rc:
    tree: cip-gitlab
    branch: 'ci/iwamatsu/linux-4.19.y-cip-rc'
    variants: *cip_variants

  cip_4.19-rt:
    tree: cip
    branch: 'linux-4.19.y-cip-rt'
    variants: *cip_variants_preempt_rt

  cip_5.10:
    tree: cip
    branch: 'linux-5.10.y-cip'
    variants:
      gcc-10:
        build_environment: gcc-10
        architectures:
          arm:
            base_defconfig: 'multi_v7_defconfig'
            extra_configs:
              - 'allnoconfig'
              - 'cip://5.10.y-cip/arm/qemu_arm_defconfig'
          arm64:
            fragments: [arm64-chromebook]
            extra_configs:
              - 'allnoconfig'
              - 'cip://5.10.y-cip/arm64/qemu_arm64_defconfig'
          x86_64:
            base_defconfig: 'x86_64_defconfig'
            fragments: [x86-chromebook]
            extra_configs:
              - 'allnoconfig'
              - 'cip://5.10.y-cip/x86/cip_qemu_defconfig'
          riscv:
            base_defconfig: 'riscv_defconfig'
            extra_configs:
              - 'allnoconfig'
              - 'cip://5.10.y-cip/riscv/qemu_riscv64_defconfig'

  cip_5.10-rc:
    tree: cip-gitlab
    branch: 'ci/iwamatsu/linux-5.10.y-cip-rc'
    variants: *cip_variants_kselftest

  cip_5.10-rt:
    tree: cip
    branch: 'linux-5.10.y-cip-rt'
    variants: *cip_variants_preempt_rt

  cip_pavel-test:
    tree: cip-gitlab
    branch: 'ci/pavel/linux-test'
    variants: *cip_variants
