rootfs_configs:
  buildroot-baseline:
    rootfs_type: buildroot
    arch_list:
      - arc
      - arm64
      - arm64be
      - armeb
      - armel
      - mipsel
      - riscv
      - x86
    frags:
      - baseline

  bullseye:
    rootfs_type: debos
    debian_release: bullseye
    arch_list:
      - amd64
      - arm64
      - armel
      - armhf
      - i386
      - mips
      - mips64el
      - mipsel
    extra_packages:
      - isc-dhcp-client
    extra_packages_remove: &extra_packages_remove_bullseye
      - bash
      - e2fslibs
      - e2fsprogs
      - klibc-utils
      - libext2fs2
      - libgnutls30
      - libklibc
      - libncursesw6
      - libp11-kit0
      - libunistring2
      - sensible-utils
    extra_files_remove: &extra_files_remove_bullseye
      - '*networkd*'
      - '*resolved*'
      - nosuspend.conf
      - tar
      - patch
      - dir
      - partx
      - find
    script: "scripts/install-bootrr.sh"
    test_overlay: "overlays/baseline"

  bullseye-firmware:
    rootfs_type: debos
    debian_release: bullseye
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages:
      - wireless-regdb
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
      - libext2fs2
    extra_firmware:
      - mrvl/pcieusb8997_combo_v4.bin
      - rockchip/dptx.bin
    test_overlay: "overlays/firmware"

  bullseye-igt:
    rootfs_type: debos
    debian_release: bullseye
    arch_list:
        - amd64
        - arm64
        - armhf
    extra_packages:
        - libcairo2
        - libdw1
        - libglib2.0-0
        - libpciaccess0
        - libprocps8
        - libudev1
        - libunwind8
    extra_packages_remove:
        - bash
        - e2fslibs
        - e2fsprogs
        - fonts-dejavu-core
        - klibc-utils
        - libext2fs2
        - libgio3.0-cil
        - libgnutls30
        - libklibc
        - libncursesw6
        - libp11-kit0
        - libunistring2
        - libx11-data
        - sensible-utils
    extra_files_remove:
        - '*networkd*'
        - '*resolved*'
        - tar
        - patch
        - diff
        - dir
        - partx
        - find
    script: "scripts/bullseye-igt.sh"
    test_overlay: "overlays/igt"

  buster:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - amd64
      - arm64
      - armel
      - armhf
      - i386
      - mips
      - mips64el
      - mipsel
    extra_packages:
      - isc-dhcp-client
    extra_packages_remove: &extra_packages_remove_buster
      - bash
      - e2fslibs
      - e2fsprogs
      - klibc-utils
      - libext2fs2
      - libgnutls30
      - libklibc
      - libncursesw6
      - libp11-kit0
      - libunistring2
      - sensible-utils
    extra_files_remove: &extra_files_remove_buster
      - '*networkd*'
      - '*resolved*'
      - nosuspend.conf
      - tar
      - patch
      - dir
      - partx
      - find
    script: "scripts/install-bootrr.sh"
    test_overlay: "overlays/baseline"

  buster-cros-ec:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages:
      - python3-minimal
      - python3-unittest2
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
      - libext2fs2
    extra_firmware:
      - mrvl/pcieusb8997_combo_v4.bin
      - mrvl/sd8897_uapsta.bin
      - qca/rampatch_00440302.bin
      - rtl_nic/rtl8153b-2.fw
      - rockchip/dptx.bin
    script: "scripts/buster-cros-ec-tests.sh"
    test_overlay: ""

  buster-igt:
    rootfs_type: debos
    debian_release: buster
    arch_list:
        - amd64
        - arm64
        - armhf
        - mips
    extra_packages:
        - libcairo2
        - libdw1
        - libglib2.0-0
        - libpciaccess0
        - libprocps7
        - libudev1
        - libunwind8
    extra_packages_remove:
        - bash
        - e2fslibs
        - e2fsprogs
        - fonts-dejavu-core
        - klibc-utils
        - libext2fs2
        - libgio3.0-cil
        - libgnutls30
        - libklibc
        - libncursesw6
        - libp11-kit0
        - libunistring2
        - libx11-data
        - sensible-utils
    extra_files_remove:
        - '*networkd*'
        - '*resolved*'
        - tar
        - patch
        - diff
        - dir
        - partx
        - find
    extra_firmware:
        - i915/bxt_dmc_ver1_07.bin
        - i915/kbl_dmc_ver1_04.bin
        - i915/glk_dmc_ver1_04.bin
    script: "scripts/buster-igt.sh"
    test_overlay: "overlays/igt"

  buster-kselftest:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages:
      - bc
      - ca-certificates
      - iproute2
      - jdim
      - libatm1
      - libcap2-bin
      - libelf1
      - libgdbm-compat4
      - libgdbm6
      - libhugetlbfs0
      - libmnl0
      - libpam-cap
      - libpcre2-8-0
      - libperl5.28
      - libpsl5
      - libxtables12
      - netbase
      - openssl
      - perl
      - perl-modules-5.28
      - procps
      - publicsuffix
      - wget
      - xz-utils

  buster-libcamera:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages:
      - libevent-dev
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
    script: "scripts/buster-libcamera.sh"
    test_overlay: "overlays/libcamera"

  buster-ltp:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages:
      - gdb-minimal
      - libnuma-dev
    script: "scripts/buster-ltp.sh"

  buster-v4l2:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages:
      - libasound2
      - libelf1
      - libjpeg62-turbo
      - libudev1
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
    script: "scripts/buster-v4l2.sh"
    test_overlay: "overlays/v4l2"

  sid:
    rootfs_type: debos
    debian_release: sid
    debian_mirror: http://deb.debian.org/debian-ports
    keyring_package: debian-ports-archive-keyring
    keyring_file: /usr/share/keyrings/debian-ports-archive-keyring.gpg
    arch_list:
      - riscv64
    extra_packages_remove: &extra_packages_remove_sid
      - bash
      - e2fslibs
      - e2fsprogs
      - klibc-utils
      - libext2fs2
      - libgnutls30
      - libklibc
      - libncursesw6
      - libp11-kit0
      - sensible-utils
    extra_files_remove: *extra_files_remove_buster
