rootfs_configs:
  bookworm:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
      - armel
      - armhf
      - i386
      - mips64el
      - mipsel
    extra_packages:
      - isc-dhcp-client
    extra_packages_remove: &extra_packages_remove_bookworm
      - bash
      - e2fslibs
      - e2fsprogs
      - klibc-utils
      - libext2fs2
      - libgnutls30
      - libklibc
      - libncursesw6
      - libp11-kit0
      - libunistring2
      - sensible-utils
    extra_files_remove: &extra_files_remove_bookworm
      - '*networkd*'
      - '*resolved*'
      - nosuspend.conf
      - tar
      - patch
      - dir
      - partx
      - find
    script: "scripts/install-bootrr.sh"
    test_overlay: "overlays/baseline"

  bookworm-blktest:
    rootfs_type: debos
    debian_release: bookworm
    imagesize: 4GB
    debos_memory: 8G
    arch_list:
      - amd64
    extra_packages:
      - ca-certificates
      - ethtool
      - iproute2
      - python3-minimal
      - python3-pip
      - python3-yaml
      - python3-requests
      - python3-jinja2
      - python3-jsonschema
      - python3-flask
      - python3-flask-restful
      - e2fsprogs
      - xfsprogs
      - f2fs-tools
      - btrfs-progs
      - nvme-cli
      - nbd-client
      - nbd-server
      - dmsetup
      - ethtool
      - iproute2
      - fio
      - gawk
      - e2fslibs
      - e2fsprogs
      - fonts-dejavu-core
      - klibc-utils
      - libext2fs2
      - ncurses-bin
      - bsdextrautils
      - zutils
      - wget
      - curl
    script: "scripts/bookworm-blktest.sh"
    crush_image_options:
      - filesystem
      - hostname_tool
      - systemd
      - misc_packages
      - package_management
      - misc_directories


  bookworm-cros-ec:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages:
      - python3-minimal
      - python3-unittest2
      - tzdata
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
      - libext2fs2
    extra_firmware:
      - mrvl/pcieusb8997_combo_v4.bin
      - mrvl/sd8897_uapsta.bin
      - qca/rampatch_00440302.bin
      - rtl_nic/rtl8153b-2.fw
      - rockchip/dptx.bin
    linux_fw_version: d526e044bddaa2c2ad855c7296147e49be0ab03c
    script: "scripts/bookworm-cros-ec-tests.sh"
    test_overlay: ""

  bookworm-deqp-runner:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
      - armhf
    script: "scripts/bookworm-deqp-runner.sh"
    imagesize: 4GB
    debos_memory: 8G
    debos_scratchsize: 16G

  bookworm-fault-injection:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
      - armhf
    script: "scripts/bookworm-fault-injection.sh"

  bookworm-gst-fluster:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
      - klibc-utils
      - libext2fs2
      - libgnutls30
      - libklibc
      - libncursesw6
      - libp11-kit0
      - libunistring2
      - sensible-utils
    extra_packages:
      - ca-certificates
      - libgbm1
      - libdrm2
      - libva2
      - libva-drm2
      - libwayland-server0
      - libxau6
      - libxcb1
      - libxdmcp6
      - mesa-va-drivers
      - python3-requests
      - python3-yaml
      - unzip
      - wget
    script: "scripts/bookworm-gst-fluster.sh"
    test_overlay: "overlays/fluster"
    imagesize: 2GB
    debos_memory: 8G

  bookworm-gst-h26forge:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
      - klibc-utils
      - libext2fs2
      - libgnutls30
      - libklibc
      - libncursesw6
      - libp11-kit0
      - libunistring2
      - sensible-utils
    extra_packages:
      - ca-certificates
      - python3-requests
      - python3-yaml
      - unzip
      - wget
    script: "scripts/bookworm-gst-h26forge.sh"
    test_overlay: "overlays/h26forge"
    imagesize: 4GB
    debos_memory: 8G
    debos_scratchsize: 16G

  bookworm-igt:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
        - amd64
        - arm64
        - armhf
    extra_packages:
        - libcairo2
        - libdw1
        - libglib2.0-0
        - libpciaccess0
        - libproc2-0
        - libudev1
        - libunwind8
    extra_packages_remove:
        - bash
        - e2fslibs
        - e2fsprogs
        - fonts-dejavu-core
        - klibc-utils
        - libext2fs2
        - libgio3.0-cil
        - libgnutls30
        - libklibc
        - libncursesw6
        - libp11-kit0
        - libunistring2
        - libx11-data
        - sensible-utils
    extra_files_remove:
        - '*networkd*'
        - '*resolved*'
        - tar
        - patch
        - diff
        - dir
        - partx
        - find
    extra_firmware:
        - amdgpu/stoney_ce.bin
        - amdgpu/stoney_me.bin
        - amdgpu/stoney_mec.bin
        - amdgpu/stoney_pfp.bin
        - amdgpu/stoney_rlc.bin
        - amdgpu/stoney_sdma.bin
        - amdgpu/stoney_uvd.bin
        - amdgpu/stoney_vce.bin
        - i915/bxt_dmc_ver1_07.bin
        - i915/kbl_dmc_ver1_04.bin
        - i915/glk_dmc_ver1_04.bin
        - qcom/a630_gmu.bin
        - qcom/a630_sqe.fw
#    linux_fw_version: d526e044bddaa2c2ad855c7296147e49be0ab03c
    script: "scripts/debian-igt.sh"
    test_overlay: "overlays/igt"
    imagesize: 4GB
    debos_memory: 8G
    debos_scratchsize: 16G


  bookworm-kselftest:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages:
      - alsa-utils
      - arping
      - bc
      - bpftool
      - ca-certificates
      - ethtool
      - iperf3
      - iproute2
      - iptables
      - iputils-ping
      - jdim
      - jq
      - libasound2
      - libatm1
      - libcap2-bin
      - libelf1
      - libgdbm-compat4
      - libgdbm6
      - libhugetlbfs0
      - libmnl0
      - libnuma1
      - libpam-cap
      - libpcre2-8-0
      - libperl5.36
      - libpsl5
      - liburing2
      - libxtables12
      - netbase
      - netsniff-ng
      - net-tools
      - openssl
      - perl
      - perl-modules-5.36
      - procps
      - psmisc
      - publicsuffix
      - python3-minimal
      - python3-unittest2
      - python3-yaml
      - socat
      - tappy
      - tcpdump
      - traceroute
      - tshark
      - tpm2-tools
      - wget
      - xz-utils
    script: "scripts/bookworm-kselftest.sh"

  bookworm-libcamera:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages:
      - libevent-dev
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
    script: "scripts/bookworm-libcamera.sh"
    test_overlay: "overlays/libcamera"

  bookworm-libhugetlbfs:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
    script: "scripts/bookworm-libhugetlbfs.sh"

  bookworm-ltp:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages:
      - ca-certificates
      - curl
      - dosfstools
      - gdb-minimal
      - libnuma-dev
      - ntfs-3g
      - python3
    script: "scripts/bookworm-ltp.sh"
    imagesize: 2GB
    debos_memory: 8G

  bookworm-rt:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages:
      - libnuma1
      - procps
      - python3
      - rtla
    script: "scripts/bookworm-rt.sh"

  bookworm-tast:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
    extra_packages_remove:
      - e2fslibs
      - e2fsprogs
      - klibc-utils
      - libext2fs2
      - libgnutls30
      - libklibc
      - libncursesw6
      - libp11-kit0
      - libunistring2
      - sensible-utils
    extra_packages:
      - ca-certificates
      - libgbm1
      - libdrm2
      - libva2
      - libva-drm2
      - unzip
      - wget
    script: "scripts/bookworm-tast.sh"
    test_overlay: "overlays/tast"
    imagesize: 14GB
    debos_memory: 8G

  bookworm-v4l2:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages:
      - libasound2
      - libelf1
      - libjpeg62-turbo
      - libudev1
      - rdfind
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
    extra_firmware:
        - mediatek/mt8173/vpu_d.bin
        - mediatek/mt8173/vpu_p.bin
        - mediatek/mt8183/scp.img
        - mediatek/mt8186/scp.img
        - mediatek/mt8192/scp.img
        - mediatek/mt8195/scp.img
    script: "scripts/bookworm-v4l2.sh"
    test_overlay: "overlays/v4l2"
    imagesize: 2GB
    debos_memory: 8G

  bookworm-vdso:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
      - armel
      - armhf
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
    script: "scripts/bookworm-vdso.sh"

  bookworm-wifi:
    rootfs_type: debos
    debian_release: bookworm
    arch_list:
      - amd64
      - arm64
      - armhf
    extra_packages:
      - rfkill
      - iw
      - iproute2
    test_overlay: "overlays/wifi"

  buildroot-baseline:
    rootfs_type: buildroot
    git_url: https://github.com/kernelci/buildroot
    git_branch: main
    arch_list:
      - arc
      - arm64
      - arm64be
      - armeb
      - armel
      - mipsel
      - riscv
      - x86
    frags:
      - baseline
