rootfs_configs:

  bullseye-cros-flash:
    rootfs_type: debos
    debian_release: bullseye
    arch_list:
      - amd64
    extra_packages:
      - bzip2
      - ca-certificates
      - parted
      - wget
      - xz-utils
    test_overlay: "overlays/cros-flash"

  chromiumos-amd64-generic:
    rootfs_type: chromiumos
    board: amd64-generic
    branch: release-R100-14526.B
    arch_list:
      - amd64

  chromiumos-octopus:
    rootfs_type: chromiumos
    board: octopus
    branch: release-R100-14526.B
    serial: ttyS1
    arch_list:
      - amd64
