---
- name: Install OS dependencies
  apt:  pkg={{ item }}
        state=latest
        update_cache=yes
  with_items:
    - build-essential
    - git
    - lsb-release
    - python-apt
    - python-pip
    - python-pycurl
    - python-virtualenv
    - python2.7-dev
    - sysfsutils
  tags:
    - install
    - deps

- include: install-mongodb.yml
- include: install-redis.yml
