name: 'Staging deploy'

on:
    workflow_dispatch:
        inputs:
            SKIP_COMPILER_IMAGES:
                type: boolean
                description: 'Skip building compiler images'
                required: false
                default: false

jobs:
    prepare-staging-branches:
        runs-on: ubuntu-22.04
        environment: deploydocker
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  repository: 'kernelci/kernelci-deploy'
                  ref: 'main'
                  fetch-depth: 0
                  path: kernelci-deploy
            - name: Prepare necessary tools
              run: |
                  export DEBIAN_FRONTEND=noninteractive
                  sudo apt-get update
                  sudo apt-get install -y python3-pip git
                  pip3 install --upgrade pip
                  git config --global user.email "kernelci@kernelci.org"
                  git config --global user.name "Staging script"
            - name: Prepare staging branches
              run: |
                  cd kernelci-deploy/tools
                  ./kci-pending.py --push ${{ secrets.GHPAT}} kernelci-core --token ${{ secrets.GITHUB_TOKEN }}
                  ./kci-pending.py --push ${{ secrets.GHPAT}} kernelci-api --token ${{ secrets.GITHUB_TOKEN }}
                  ./kci-pending.py --push ${{ secrets.GHPAT}} kernelci-pipeline --token ${{ secrets.GITHUB_TOKEN }}
    call-docker-build:
        needs: prepare-staging-branches
        uses: ./.github/workflows/docker_images.yml
        secrets: inherit
        with:
            GIT_OWNER: 'kernelci'
            GIT_BRANCH: 'staging.kernelci.org'
            SKIP_COMPILER_IMAGES: ${{ inputs.SKIP_COMPILER_IMAGES }}
